# This is a basic workflow to help you get started with Actions

name: OpenSUSE Tumbleweed

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    container: opensuse/tumbleweed
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Install needed packages
      - name: Install packages
        run: |
          zypper update && zypper install wireshark wireshark-devel cmake make gcc gcc-c++

      # Runs a set of commands using the runners shell
      - name: Build project
        run: |
          cmake .
          make -j$(nproc)
          make install

      # Test, if plugin is found
      - name: Test
        run: tshark -G plugins | grep -i -E "(error|couldn)" || true
