# This is a basic workflow to help you get started with Actions

name: OpenSUSE

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Global:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: opensuse/leap:15 #${{ matrix.os }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Install needed packages
      - name: Install packages
        run: |
          zypper update -y && zypper install -y wireshark wireshark-devel cmake make gcc gcc-c++ wget sudo

      # Runs a set of commands using the runners shell
      - name: Build plugins
        run: |
          cmake -DINSTALL_PLUGIN_LOCAL=OFF .
          make -j$(nproc)
          sudo make install

      - name: Check if plugin is installed correctly
        run: tshark -G plugins | grep -E "VCDReader.so.*"

      - name: Test plugins for error
        run: '! tshark -G plugins 2>&1 >/dev/null | grep -i -E "(error|couldn)"'
